version: '2'
services:

  web:
    image: "ansible/awx_web:${AWX_VERSION}"
    container_name: awx_web
    depends_on:
      - rabbitmq
      - mawxemcached
      - postgres
    ports:
      - 8052:8052
    hostname: awx web
    user: root
    restart: unless-stopped
    volumes:
      - "${AWX_DATA}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${AWX_DATA}/environment.sh:/etc/tower/conf.d/environment.sh"
      - "${AWX_DATA}/credentials.py:/etc/tower/conf.d/credentials.py"
      - "${AWX_PROJECTS}:/var/lib/awx/projects"

  task:
    image: "ansible/awx_task:${AWX_VERSION}"
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx 
    user: root
    restart: unless-stopped
    volumes:
      - "${AWX_DATA}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${AWX_DATA}/environment.sh:/etc/tower/conf.d/environment.sh"
      - "${AWX_DATA}/credentials.py:/etc/tower/conf.d/credentials.py"
      - "${AWX_PROJECTS}:/var/lib/awx/projects"

  rabbitmq:
    image: rabbitmq:3.7 
    container_name: awx_rabbitmq
    restart: unless-stopped
    env_file:
      - awx.env

  memcached:
    image: memcached:1.5-alpine
    container_name: awx_memcached
    restart: unless-stopped

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    env_file:
      - awx.env
