version: '2'
services:

  web:
    image: "ansible/awx_web:${AWX_VERSION}"
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - 8052:8052
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "${AWX_DATA}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${AWX_DATA}/environment.sh:/etc/tower/conf.d/environment.sh"
      - "${AWX_DATA}/credentials.py:/etc/tower/conf.d/credentials.py"
      - "${AWX_PROJECTS}:/var/lib/awx/projects"

  task:
    image: "ansible/awx_task:${AWX_VERSION}"
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx 
    user: root
    restart: unless-stopped
    volumes:
      - "${AWX_DATA}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${AWX_DATA}/environment.sh:/etc/tower/conf.d/environment.sh"
      - "${AWX_DATA}/credentials.py:/etc/tower/conf.d/credentials.py"
      - "${AWX_PROJECTS}:/var/lib/awx/projects"

  rabbitmq:
    image: rabbitmq:3.7
    restart: unless-stopped
    env_file:
      - awx.env

  memcached:
    image: memcached:alpine
    restart: unless-stopped

  postgres:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - ./psql-data:/var/lib/postgresql/data/pgdata:Z
    env_file:
      - awx.env
